# Generated by Django 3.2.16 on 2022-12-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('sobrenome', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('funcionarios', models.CharField(blank=True, choices=[('BlackJack', 'Junin Black'), ('Pedro', 'Pedro lucas')], max_length=100, null=True)),
                ('data', models.DateField()),
                ('hora', models.CharField(choices=[('08:00 às 09:00', '08:00 às 09:00'), ('09:00 às 10:00', '09:00 às 10:00'), ('10:00 às 11:00', '10:00 às 11:00'), ('11:00 às 12:00', '11:00 às 12:00'), ('13:00 às 14:00', '13:00 às 14:00'), ('14:00 às 15:00', '14:00 às 15:00'), ('15:00 às 16:00', '15:00 às 16:00'), ('16:00 às 17:00', '16:00 às 17:00'), ('17:00 às 18:00', '17:00 às 18:00'), ('18:00 às 19:00', '18:00 às 19:00')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=120)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('usuario', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=256)),
                ('nascimento', models.DateField()),
                ('tel', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos_preenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seuapp.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seuapp.servicos')),
            ],
        ),
        migrations.AddField(
            model_name='servicos',
            name='preenchido',
            field=models.ManyToManyField(through='seuapp.Servicos_preenchido', to='seuapp.Agendamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seuapp.usuario'),
        ),
    ]
