# Generated by Django 4.1.1 on 2022-11-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.CharField(choices=[('08:00 às 09:00', '08:00 às 09:00'), ('09:00 às 10:00', '09:00 às 10:00'), ('10:00 às 11:00', '10:00 às 11:00'), ('11:00 às 12:00', '11:00 às 12:00'), ('13:00 às 14:00', '13:00 às 14:00'), ('14:00 às 15:00', '14:00 às 15:00'), ('15:00 às 16:00', '15:00 às 16:00'), ('16:00 às 17:00', '16:00 às 17:00'), ('17:00 às 18:00', '17:00 às 18:00'), ('18:00 às 19:00', '18:00 às 19:00')], max_length=100),
        ),
    ]
